site_name: "FAST API Template"

nav:
  - About: index.md
  - Examples: examples.md
  - Help: help.md

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggestions
    - search.highlight
    - content.code.copy

